### ISSUE TITLE
Jobtastic with Flask

### ISSUE THREAD

**Issue by ezanaty** [PolicyStat/jobtastic#55] opened 2016-02-24 12:41 UTC
in my project i don't have django, I just have backend implemented using Flask.
when i am trying to try the example with flask, I've runtime error due to lack of django settings.

`
from jobtastic import JobtasticTask
  File "/usr/local/lib/python2.7/dist-packages/jobtastic/__init__.py", line 17, in <module>
    from jobtastic.task import JobtasticTask  # NOQA
  File "/usr/local/lib/python2.7/dist-packages/jobtastic/task.py", line 35, in <module>
    from django.core.cache import cache
  File "/usr/lib/python2.7/dist-packages/django/core/cache/__init__.py", line 69, in <module>
    if DEFAULT_CACHE_ALIAS not in settings.CACHES:
  File "/usr/lib/python2.7/dist-packages/django/conf/__init__.py", line 54, in __getattr__
    self._setup(name)
  File "/usr/lib/python2.7/dist-packages/django/conf/__init__.py", line 47, in _setup
    % (desc, ENVIRONMENT_VARIABLE))
django.core.exceptions.ImproperlyConfigured: Requested setting CACHES, but settings are not configured. You must either define the environment variable DJANGO_SETTINGS_MODULE or call settings.configure() before accessing settings.

Process finished with exit code 1
`

will i be able to use the jobtastic ?

**Comment by ezanaty** [comment] 2016-02-24 12:41
@winhamwr

**Comment by winhamwr** [comment] 2016-02-24 16:58
Hello ezanaty,

Jobtastic definitely aims to be compatible with Flask and not require Django. [this try block](https://github.com/PolicyStat/jobtastic/blob/master/jobtastic/task.py#L37) is supposed to be automatically detecting that Django isn't configured and then falling back to Flask. I think the problem is that it does that by just detecting if Django is installed.

Can you try removing Django from your virtualenv and see if that fixes it?

It's not a "real solution" but it might be a work-around.

Thanks
-Wes

**Comment by kareemyousef** [comment] 2016-06-15 14:50
@winhamwr Thank you!. Your answer is really helpful!

**Comment by winhamwr** [comment] 2016-09-01 20:42
With #63 now merged in, I think we've achieved Django-free operation.

**Closed by winhamwr** 2016-09-01 20:42 UTC
